FROM microsoft/dotnet:sdk as build-env
WORKDIR /app

# copy csproj and restore as distinct layers
COPY ./ImagehuntBotBuilder/*.csproj ./ImagehuntBotBuilder/
COPY ./ImageHuntCore/*.csproj ./ImageHuntCore/
COPY ./ImageHuntWebServiceClient/*.csproj ./ImageHuntWebServiceClient/

RUN dotnet restore ./ImagehuntBotBuilder/ImageHuntBotBuilder.csproj

# copy and build everything else
COPY . ./
RUN dotnet publish ./ImagehuntBotBuilder/ImageHuntBotBuilder.csproj -c Release -o /app/out

FROM microsoft/dotnet:aspnetcore-runtime
WORKDIR /app
COPY --from=build-env /app/out .

#ENTRYPOINT ["dotnet", "ImageHuntBotBuilder.dll"]